const JSON_HEADERS={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:JSON_HEADERS});
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const types=['신규 롤 제작','보수·재가공','피복·표면 가공','장치·거치대 제작','장치 제작','기타 제작 상담'];
async function identity(req){const id=req.headers.get('oai-authenticated-user-id');if(!id)return null;const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(id));return {id:[...new Uint8Array(digest)].map(n=>n.toString(16).padStart(2,'0')).join(''),admin:req.headers.get('oai-authenticated-user-email')?.toLowerCase()==='eva@hnf.co.kr'};}
async function boundedForm(req){const limit=42*1024*1024;if(Number(req.headers.get('content-length'))>limit)throw new Error('첨부파일 총 용량을 줄여주세요.');const reader=req.body?.getReader();if(!reader)throw new Error('요청 내용이 없습니다.');let total=0,chunks=[];while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>limit){await reader.cancel();throw new Error('첨부파일 총 용량을 줄여주세요.');}chunks.push(value);}return new Response(new Blob(chunks),{headers:{'Content-Type':req.headers.get('content-type')||''}}).formData();}
async function findRecord(bucket,user,id){if(!uuid.test(id))return null;let key=`requests/${user.id}/${id}.json`;let record=await bucket.get(key);if(!record&&user.admin){let cursor;do{const page=await bucket.list({prefix:'requests/',cursor,limit:1000});const match=page.objects.find(x=>x.key.endsWith('/'+id+'.json'));if(match){key=match.key;record=await bucket.get(key);break;}cursor=page.truncated?page.cursor:undefined;}while(cursor);}if(!record)return null;return {key,data:await record.json()};}
export default {async fetch(req,env){const u=new URL(req.url);if(!u.pathname.startsWith('/api/'))return env.ASSETS?env.ASSETS.fetch(req):new Response('Not found',{status:404});
 const user=await identity(req);if(!user)return json({error:'로그인한 계정으로 접수해 주세요.'},401);
 if(!env.BUCKET)return json({error:'접수 저장소를 사용할 수 없습니다. 입력을 유지하고 잠시 후 다시 시도해 주세요.'},503);
 if(!['GET','HEAD'].includes(req.method)&&req.headers.get('origin')!==u.origin)return json({error:'잘못된 요청 출처입니다.'},403);
 try{
 if(u.pathname==='/api/requests'&&req.method==='GET'){const items=[];let cursor;do{const page=await env.BUCKET.list({prefix:user.admin?'requests/':`requests/${user.id}/`,limit:100,cursor});for(const item of page.objects){const obj=await env.BUCKET.get(item.key);if(obj)items.push(await obj.json());}cursor=page.truncated?page.cursor:undefined;}while(cursor&&items.length<100);items.sort((a,b)=>b.created.localeCompare(a.created));return json({items:items.map(({owner,...r})=>r),admin:user.admin});}
 if(u.pathname==='/api/requests'&&req.method==='POST'){
 const f=await boundedForm(req);const id=String(f.get('requestId')||'');if(!uuid.test(id))return json({error:'올바른 접수 번호가 아닙니다. 페이지를 새로고침해 주세요.'},400);
 const key=`requests/${user.id}/${id}.json`;if(await env.BUCKET.head(key))return json({id},200);
 const text=(k,max,required=true)=>{const value=String(f.get(k)||'').trim();if((required&&!value)||value.length>max)throw new Error(`${k}: 입력 내용을 확인하세요.`);return value;};
 const company=text('company',100),name=text('name',60),email=text('email',180),phone=text('phone',40),type=text('type',50),message=text('message',5000),material=text('material',150,false),due=text('due',10,false),quantity=Number(f.get('quantity'));
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!types.includes(type)||!Number.isInteger(quantity)||quantity<1||quantity>100000||f.get('consent')!=='on'||(due&&!/^\d{4}-\d{2}-\d{2}$/.test(due)))return json({error:'연락처, 수량, 동의 항목을 확인하세요.'},400);
 const files=f.getAll('files');if(files.length>11||files.some(x=>typeof x==='string'||!x.size||x.size>20*1024*1024)||files.reduce((s,x)=>s+x.size,0)>41*1024*1024)return json({error:'첨부파일 개수와 용량을 확인하세요.'},400);
 if(files.some(x=>!/^.+\.(pdf|png|jpe?g|webp|dxf|dwg|step|stp|iges|igs|stl|json|svg|zip|txt)$/i.test(x.name)))return json({error:'지원하지 않는 첨부파일 형식입니다.'},400);
 const stored=[];try{for(let i=0;i<files.length;i++){const file=files[i],path=`uploads/${user.id}/${id}/${i}`;await env.BUCKET.put(path,file.stream(),{httpMetadata:{contentType:'application/octet-stream'}});stored.push({name:file.name.replace(/[\r\n\x00-\x1f]/g,'').slice(0,200),size:file.size,key:path});}const record={id,owner:user.id,company,name,email,phone,type,message,material,due,quantity,created:new Date().toISOString(),files:stored};await env.BUCKET.put(key,JSON.stringify(record),{httpMetadata:{contentType:'application/json'}});}catch(err){await Promise.all(stored.map(x=>env.BUCKET.delete(x.key)));throw err;}return json({id},201);
 }
 const match=u.pathname.match(/^\/api\/requests\/([^/]+)(?:\/files\/(\d+))?$/);if(match){const found=await findRecord(env.BUCKET,user,match[1]);if(!found)return json({error:'접수 내역을 찾을 수 없습니다.'},404);if(req.method==='DELETE'&&!match[2]){for(const f of found.data.files)await env.BUCKET.delete(f.key);await env.BUCKET.delete(found.key);return json({deleted:true});}if(req.method==='GET'&&match[2]!=null){const f=found.data.files[Number(match[2])];if(!f)return json({error:'파일을 찾을 수 없습니다.'},404);const obj=await env.BUCKET.get(f.key);if(!obj)return json({error:'파일을 찾을 수 없습니다.'},404);return new Response(obj.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.name).replace(/'/g,'%27')}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox"}});}}
 return json({error:'지원하지 않는 요청입니다.'},404);
 }catch(e){console.error('inquiry request failed',e.name);return json({error:e.message?.includes('입력')||e.message?.includes('첨부')?e.message:'접수 처리에 실패했습니다. 입력은 유지됩니다. 다시 시도해 주세요.'},400);}
}};
